# Generated by Django 3.0.8 on 2020-08-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sdefault_treet_address2',
            new_name='default_street_address2',
        ),
    ]
