# Generated by Django 3.0.8 on 2020-08-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200814_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_shopping_bag',
            new_name='original_bag',
        ),
    ]
